### ISSUE TITLE
示例项目启动失败

### ISSUE THREAD

**Issue by iamyus** [X-Profiler/xprofiler-docker#5]
在本地环境拉取代码不做任何改动 docker-compse up -d

![image](https://user-images.githubusercontent.com/29141080/164169539-0b7ea70c-358d-43c8-8c14-20bd6d115741.png)

xtransit-mysql、xprofiler-console、xtransit-manager 一直在不断的 running、restarting

换了两个机器 mac intel、mac m1 都是这样 是本地环境的问题吗？

**Comment by iamyus** [comment]
xprofiler-console 的 log 为

2022-04-20 07:06:20,907 ERROR 47 [-/127.0.0.1/-/1ms GET /] nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND xtransit-mysql

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

    --------------------

    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)

    at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)

    at PoolConnection.connect (/app/node_modules/mysql/lib/Connection.js:116:18)

    at Pool.getConnection (/app/node_modules/mysql/lib/Pool.js:48:16)

    at /app/node_modules/ali-rds/node_modules/pify/index.js:29:7

    at new Promise (<anonymous>)

    at Pool.<anonymous> (/app/node_modules/ali-rds/node_modules/pify/index.js:12:10)

    at Pool.ret [as getConnection] (/app/node_modules/ali-rds/node_modules/pify/index.js:56:34)

    at Pool.query (/app/node_modules/mysql/lib/Pool.js:202:8)

    at /app/node_modules/ali-rds/node_modules/pify/index.js:29:7

    sql: select now() as currentTime;

errno: "ENOTFOUND"

code: "ENOTFOUND"

syscall: "getaddrinfo"

hostname: "xtransit-mysql"

fatal: true

name: "ENOTFOUNDError"

pid: 47

hostname: xprofiler-console


2022-04-20 07:06:20,908 ERROR 47 nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND xtransit-mysql

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

    --------------------

    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)

    at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)

    at PoolConnection.connect (/app/node_modules/mysql/lib/Connection.js:116:18)

    at Pool.getConnection (/app/node_modules/mysql/lib/Pool.js:48:16)

    at /app/node_modules/ali-rds/node_modules/pify/index.js:29:7

    at new Promise (<anonymous>)

    at Pool.<anonymous> (/app/node_modules/ali-rds/node_modules/pify/index.js:12:10)

    at Pool.ret [as getConnection] (/app/node_modules/ali-rds/node_modules/pify/index.js:56:34)

    at Pool.query (/app/node_modules/mysql/lib/Pool.js:202:8)

    at /app/node_modules/ali-rds/node_modules/pify/index.js:29:7

    sql: select now() as currentTime;

errno: "ENOTFOUND"

code: "ENOTFOUND"

syscall: "getaddrinfo"

hostname: "xtransit-mysql"

fatal: true

name: "ENOTFOUNDError"

pid: 47

hostname: xprofiler-console


2022-04-20 07:06:20,909 ERROR 47 [app_worker] start error, exiting with code:1

2022-04-20 07:06:20,958 INFO 47 [app_worker] receive signal SIGTERM, exiting with code:0

2022-04-20 07:06:20,966 INFO 47 [app_worker] beforeExit success

2022-04-20 07:06:20,966 INFO 47 [app_worker] exit with code:0

[2022-04-20 07:06:20.986] [cfork:master:29] worker:47 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)

[2022-04-20 07:06:20.987] [cfork:master:29] don't fork, because worker:47 will be kill soon

2022-04-20 07:06:20,987 INFO 29 [master] app_worker#1:47 disconnect, suicide: false, state: disconnected, current workers: ["1"]

[2022-04-20 07:06:20.989] [cfork:master:29] worker:47 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)

2022-04-20 07:06:20,991 ERROR 29 nodejs.AppWorkerDiedError: [master] app_worker#1:47 died (code: 0, signal: null, suicide: false, state: dead), current workers: []

    at Master.onAppExit (/app/node_modules/egg-cluster/lib/master.js:510:21)

    at Master.emit (events.js:315:20)

    at Messenger.sendToMaster (/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)

    at Messenger.send (/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)

    at EventEmitter.<anonymous> (/app/node_modules/egg-cluster/lib/master.js:353:22)

    at EventEmitter.emit (events.js:327:22)

    at ChildProcess.<anonymous> (internal/cluster/master.js:190:13)

    at Object.onceWrapper (events.js:422:26)

    at ChildProcess.emit (events.js:315:20)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

name: "AppWorkerDiedError"

pid: 29

hostname: xprofiler-console


2022-04-20 07:06:20,994 ERROR 29 [master] app_worker#1:47 start fail, exiting with code:1

2022-04-20 07:06:20,994 ERROR 29 [master] exit with code:1

2022-04-20 07:06:21,007 ERROR 36 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110

2022-04-20 07:06:21,011 INFO 36 [agent_worker] beforeExit success

2022-04-20 07:06:21,011 ERROR 36 [agent_worker] exit with code:110

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! xprofiler-console@1.0.0 start: `egg-scripts start --title=egg-server-xprofiler-console --workers=1 --port=8443`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the xprofiler-console@1.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2022-04-20T07_06_21_051Z-debug.log

**Comment by hyj1991** [comment]
参照文档走独立部署，`docker` 目前没有官方做维护，因此都没放文档里

**Comment by hyj1991** [comment]
https://www.yuque.com/hyj1991/easy-monitor/deployment

**Comment by iamyus** [comment]
> 参照文档走独立部署，`docker` 目前没有官方做维护，因此都没放文档里

好的  `docker` 部署方案后续官方有维护计划吗？

**Comment by hyj1991** [comment]
> 好的 docker 部署方案后续官方有维护计划吗？

有肯定有的，不过最近没有精力做这个，docker 镜像官方维护的话，每次更新都要重新 push 保持更新，现在我一个人不一定兼顾的了，因此一直没有动手。

目前还是优先保障一些新功能的迭代。
